import { defineStore } from "pinia";
// found it from google! https://www.npmjs.com/package/generate-unique-id
import generateUniqueId from "generate-unique-id";
// create a numbers-only id
// const id = generateUniqueId({
//   useLetters: false
// });

const default_user = {
  id: 1,
  name: "Default User",
  email: "default@example.com",
  phone: "0123456789",
  password: "DefaultUser123",
};

export const useAuthStore = defineStore("auth", {
  //state
  state: () => ({
    /* --------- load users from local storage or set the default value --------- */
    // 'users' is the database of our registered users
    users: JSON.parse(localStorage.getItem("users")) || [default_user],
    // 'currentUser' is the user who is currently signed in
    currentUser: JSON.parse(localStorage.getItem("currentUser")) || null,
    // 'isLoggedIn' is simply a boolean key
    isLoggedIn: JSON.parse(localStorage.getItem("isLoggedIn")) || false,
  }),

  //getters
  getters: {},

  //actions
  actions: {
    /* --------- checking validation | All the regex are generated by AI -------- */
    isNameValid(name) {
      // at least 2 characters, letters and spaces only
      return /^[A-Za-z\s]{2,50}$/.test(name.trim());
    },
    isEmailValid(email) {
      // default email format
      return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
    },
    isPhoneValid(phone) {
      // 10 or 11 (optional leading 0) digits total
      return /^0?[0-9]{10}$/.test(phone);
    },
    isPasswordValid(password) {
      // at least: 9 chars, 1 uppercase, 1 lowercase, 1 number
      return /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{9,}$/.test(password);
    },

    /* --------------------------------- sign in -------------------------------- */
    signin(identifier, password) {
      // if (!identifier.trim()) {
      //   return {
      //     success: false,
      //     message: "Email or phone is required",
      //   };
      // }

      // if (!password.trim()) {
      //   return {
      //     success: false,
      //     message: "Password is required",
      //   };
      // }

      const user = this.users.find(
        (user) =>
          (user.email === identifier || user.phone === identifier) &&
          user.password === password,
      );

      // if (!user) {
      //   return {
      //     success: false,
      //     message: "Invalid credentials",
      //   };
      // }

      this.currentUser = user;
      this.isLoggedIn = true;

      localStorage.setItem("currentUser", JSON.stringify(user));

      localStorage.setItem("isLoggedIn", JSON.stringify(true));

      return {
        success: true,
      };
    },
  },
});
